name: Update the blog list

on:
  push:
    branches: [main]

jobs:
  update-blog-list:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.6

      - name: Run Python script that will update the blog list
        run: |
          python update_article.py
          # python -c "import os; print(os.getcwd())"

      - name: Commit files
        run: |
          git config --local user.email "88028802+quanmcpc-blog@users.noreply.github.com"
          git config --local user.name "quanmcpc-blog"
          git commit -m "Update blog list" -a --allow-empty

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
